from datetime import datetime


def add_export_footer(report: str) -> str:
    return report + f"\n\n---\nGenerated by prototype on {datetime.utcnow().isoformat()} UTC. Uses synthetic or user-provided data in-memory only."
